<?php


use Phinx\Seed\AbstractSeed;

class CreateProducts extends AbstractSeed
{

    public function run()
    {
        $categories = [
            [
                'name'    => 'Website Template',
                'slug'    => 'website-template',
                'status' => 1,
                'created_at' => '2018-01-30 16:30:45',
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name'    => 'WordPress Theme',
                'slug'    => 'wordpress-theme',
                'status' => 1,
                'created_at' => '2018-01-30 16:30:45',
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name'    => 'UI Kits',
                'slug'    => 'ui-kits',
                'status' => 1,
                'created_at' => '2018-01-30 16:30:45',
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name'    => 'Graphics',
                'slug'    => 'graphics',
                'status' => 1,
                'created_at' => '2018-01-30 16:30:45',
                'updated_at' => date('Y-m-d H:i:s'),
            ],
        ];
        $categoriesTable = $this->table('categories');
        $categoriesTable->insert($categories)
            ->save();

        $products = [
            [
                'uuid'    => 'ae6366cc-d14b-4e6f-8d43-bfd330eb6141',
                'title'    => 'Car Zone - Car Dealer HTML Template',
                'slug'    => 'car-zone-car-dealer-html-template',
                'category_id' => 1,
                'user_id' => null,
                'thumb_image' => 'attachments/ae6366cc-d14b-4e6f-8d43-bfd330eb6141/thumb.jpg',
                'main_image' => 'attachments/ae6366cc-d14b-4e6f-8d43-bfd330eb6141/main.jpg',
                'demo_url' => 'http://demo.themevessel.com/car-shop',
                'description' => 'Some methods in this library have requirements due to integer size restrictions on 32-bit and 64-bit builds of PHP. A 64-bit build of PHP and the Moontoast\Math library are recommended. However, this library is designed to work on 32-bit builds of PHP without Moontoast\Math, with some degraded functionality. Please check the API documentation for more information.',
                'price' => 2.20,
                'sales' => 5,
                'rating' => 4.5,
                'total_viewed' => 100,
                'download_path' => '/var/www/html/themevessel-shop/templates/download_items/car-zone-car-dealer-html-template.zip',
                'version' => '1.0.1',
                'tags' => 'bootstrap, bootstrap 4, car dealer, automotive, auto car, car',
                'layout' => 'Responsive',
                'product_type' => 'paid',
                'key_features' => 'Responsive Layout,  Documentation, Bootstrap 3.x, Retina Ready',
                'browsers_compatible' => ' IE10, IE11, Edge, Chrome Firefox, Safari, Opera',
                'is_featured' => 1,
                'status' => 1,
                'meta_title' => 'Meta - Title',
                'meta_description' => 'Meta - Description',
                'meta_image' => 'Meta - image',
                'created_at' => '2018-01-30 16:30:45',
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'uuid'    => 'ee6366cc-d14b-4e6f-8d43-bfd3304b6121',
                'title'    => 'Auto Car - Car Dealer HTML Template',
                'slug'    => 'auto-car-estate-html-template',
                'category_id' => 1,
                'user_id' => null,
                'thumb_image' => 'attachments/ee6366cc-d14b-4e6f-8d43-bfd3304b6121/thumb.jpg',
                'main_image' => 'attachments/ee6366cc-d14b-4e6f-8d43-bfd3304b6121/main.jpg',
                'demo_url' => 'http://demo.themevessel.com/car-shop',
                'description' => 'Some methods in this library have requirements due to integer size restrictions on 32-bit and 64-bit builds of PHP. A 64-bit build of PHP and the Moontoast\Math library are recommended. However, this library is designed to work on 32-bit builds of PHP without Moontoast\Math, with some degraded functionality. Please check the API documentation for more information.',
                'price' => 5.00,
                'sales' => 25,
                'rating' => 3.5,
                'total_viewed' => 1200,
                'download_path' => '/var/www/html/themevessel-shop/templates/download_items/auto-car-estate-html-template.zip',
                'version' => '1.0.5',
                'tags' => 'bootstrap, bootstrap 4, car dealer, automotive, auto car, car',
                'layout' => 'Responsive',
                'product_type' => 'paid',
                'key_features' => 'Responsive Layout,  Documentation, Bootstrap 3.x, Retina Ready',
                'browsers_compatible' => ' IE10, IE11, Edge, Chrome Firefox, Safari, Opera',
                'is_featured' => 1,
                'status' => 1,
                'meta_title' => 'Meta - Title',
                'meta_description' => 'Meta - Description',
                'meta_image' => 'Meta - image',
                'created_at' => '2018-01-30 16:30:45',
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'uuid'    => 'ae6366cc-d14b-4e6f-8d43-bfd3304b6141',
                'title'    => 'Realty - Real Estate HTML Template',
                'slug'    => 'realty-real-estate-html-template',
                'category_id' => 2,
                'user_id' => null,
                'thumb_image' => 'attachments/ae6366cc-d14b-4e6f-8d43-bfd3304b6141/thumb.jpg',
                'main_image' => 'attachments/ae6366cc-d14b-4e6f-8d43-bfd3304b6141/main.jpg',
                'demo_url' => 'http://demo.themevessel.com/car-shop',
                'description' => 'Some methods in this library have requirements due to integer size restrictions on 32-bit and 64-bit builds of PHP. A 64-bit build of PHP and the Moontoast\Math library are recommended. However, this library is designed to work on 32-bit builds of PHP without Moontoast\Math, with some degraded functionality. Please check the API documentation for more information.',
                'price' => 4.10,
                'sales' => 5,
                'rating' => 4.1,
                'total_viewed' => 1100,
                'download_path' => '/var/www/html/themevessel-shop/templates/download_items/realty-real-estate-html-template.zip',
                'version' => '1.0.1',
                'tags' => 'bootstrap, bootstrap 4, real estate, properties, real estate agency',
                'layout' => 'Responsive',
                'product_type' => 'paid',
                'key_features' => 'Responsive Layout,  Documentation, Bootstrap 3.x, Retina Ready',
                'browsers_compatible' => ' IE10, IE11, Edge, Chrome Firefox, Safari, Opera',
                'is_featured' => 0,
                'status' => 1,
                'meta_title' => 'Meta - Title',
                'meta_description' => 'Meta - Description',
                'meta_image' => 'Meta - image',
                'created_at' => '2018-01-30 16:30:45',
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'uuid'    => 'ae6366cc-d14b-4e6f-8d43-bfd3304b6121',
                'title'    => 'The Nest - Real Estate HTML Template',
                'slug'    => 'the-nest-estate-html-template',
                'category_id' => 3,
                'user_id' => null,
                'thumb_image' => 'attachments/ae6366cc-d14b-4e6f-8d43-bfd3304b6121/thumb.jpg',
                'main_image' => 'attachments/ae6366cc-d14b-4e6f-8d43-bfd3304b6121/main.jpg',
                'demo_url' => 'http://demo.themevessel.com/car-shop',
                'description' => 'Some methods in this library have requirements due to integer size restrictions on 32-bit and 64-bit builds of PHP. A 64-bit build of PHP and the Moontoast\Math library are recommended. However, this library is designed to work on 32-bit builds of PHP without Moontoast\Math, with some degraded functionality. Please check the API documentation for more information.',
                'price' => 7.00,
                'sales' => 50,
                'rating' => 4.5,
                'total_viewed' => 100,
                'download_path' => '/var/www/html/themevessel-shop/templates/download_items/the-nest-estate-html-template.zip',
                'tags' => 'bootstrap, bootstrap 4, real estate, properties, real estate agency',
                'version' => '1.0.1',
                'layout' => 'Responsive',
                'product_type' => 'paid',
                'key_features' => 'Responsive Layout,  Documentation, Bootstrap 3.x, Retina Ready',
                'browsers_compatible' => ' IE10, IE11, Edge, Chrome Firefox, Safari, Opera',
                'is_featured' => 0,
                'status' => 1,
                'meta_title' => 'Meta - Title',
                'meta_description' => 'Meta - Description',
                'meta_image' => 'Meta - image',
                'created_at' => '2018-01-30 16:30:45',
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'uuid'    => 'ae6366c1-d14b-4e6f-8d43-bfd3304b6121',
                'title'    => 'Hotel Alpha - Hotel HTML Responsive Template',
                'slug'    => 'hotel-alpha-hotel-responsive-template',
                'category_id' => 1,
                'user_id' => null,
                'thumb_image' => 'attachments/ae6366c1-d14b-4e6f-8d43-bfd3304b6121/thumb.jpg',
                'main_image' => 'attachments/ae6366c1-d14b-4e6f-8d43-bfd3304b6121/main.jpg',
                'demo_url' => 'http://demo.themevessel.com/car-shop',
                'description' => 'Some methods in this library have requirements due to integer size restrictions on 32-bit and 64-bit builds of PHP. A 64-bit build of PHP and the Moontoast\Math library are recommended. However, this library is designed to work on 32-bit builds of PHP without Moontoast\Math, with some degraded functionality. Please check the API documentation for more information.',
                'price' => 8.00,
                'sales' => 5,
                'rating' => 4.5,
                'total_viewed' => 100,
                'download_path' => '/var/www/html/themevessel-shop/templates/download_items/hotel-alpha-hotel-responsive-template.zip',
                'tags' => 'bootstrap, bootstrap 4, hotel, hotel listing',
                'version' => '1.0.1',
                'layout' => 'Responsive',
                'product_type' => 'paid',
                'key_features' => 'Responsive Layout,  Documentation, Bootstrap 3.x, Retina Ready',
                'browsers_compatible' => ' IE10, IE11, Edge, Chrome Firefox, Safari, Opera',
                'is_featured' => 0,
                'status' => 1,
                'meta_title' => 'Meta - Title',
                'meta_description' => 'Meta - Description',
                'meta_image' => 'Meta - image',
                'created_at' => '2018-01-30 16:30:45',
                'updated_at' => date('Y-m-d H:i:s'),
            ]
        ];
        $productsTable = $this->table('products');
        $productsTable->insert($products)
            ->save();
    }
}
