<?php


use Phinx\Seed\AbstractSeed;

class QuestionsSeeder extends AbstractSeed
{
    /**
     * Run Method.
     *
     * Write your database seeder using this method.
     *
     * More information on writing seeders is available here:
     * http://docs.phinx.org/en/latest/seeding.html
     */
    public function run()
    {
        $questions = [
            [
                'survey_id' => 1,
                'question' => 'Office entry without ID card (Retina scan, proximity sensor etc.]',
                'impact_group_size' => 10,
                'occurrence_frequency' => 10,
                'experience_impact' => 10,
                'business_impact' => 10,
                'financial_feasibility' => 10,
                'technical_feasibility' => 10,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'survey_id' => 1,
                'question' => 'Virtual personal assistant for every employees',
                'impact_group_size' => 10,
                'occurrence_frequency' => 10,
                'experience_impact' => 10,
                'business_impact' => 10,
                'financial_feasibility' => 10,
                'technical_feasibility' => 10,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'survey_id' => 1,
                'question' => 'Deep Curated learning based on role, skill and aspiration',
                'impact_group_size' => 10,
                'occurrence_frequency' => 10,
                'experience_impact' => 10,
                'business_impact' => 10,
                'financial_feasibility' => 10,
                'technical_feasibility' => 10,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'survey_id' => 1,
                'question' => 'Washroom clean-up based on censors',
                'impact_group_size' => 10,
                'occurrence_frequency' => 10,
                'experience_impact' => 10,
                'business_impact' => 10,
                'financial_feasibility' => 10,
                'technical_feasibility' => 10,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'survey_id' => 1,
                'question' => 'Meeting minutes on voice command and sent to recipients',
                'impact_group_size' => 10,
                'occurrence_frequency' => 10,
                'experience_impact' => 10,
                'business_impact' => 10,
                'financial_feasibility' => 10,
                'technical_feasibility' => 10,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'survey_id' => 1,
                'question' => 'Online employee community for different reference & recommendations',
                'impact_group_size' => 10,
                'occurrence_frequency' => 10,
                'experience_impact' => 10,
                'business_impact' => 10,
                'financial_feasibility' => 10,
                'technical_feasibility' => 10,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'survey_id' => 1,
                'question' => 'Gamification in employee onboarding',
                'impact_group_size' => 10,
                'occurrence_frequency' => 10,
                'experience_impact' => 10,
                'business_impact' => 10,
                'financial_feasibility' => 10,
                'technical_feasibility' => 10,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'survey_id' => 1,
                'question' => 'Gamification to cultivate collaboration',
                'impact_group_size' => 10,
                'occurrence_frequency' => 10,
                'experience_impact' => 10,
                'business_impact' => 10,
                'financial_feasibility' => 10,
                'technical_feasibility' => 10,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'survey_id' => 1,
                'question' => 'Contextual rewards for employees',
                'impact_group_size' => 10,
                'occurrence_frequency' => 10,
                'experience_impact' => 10,
                'business_impact' => 10,
                'financial_feasibility' => 10,
                'technical_feasibility' => 10,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'survey_id' => 1,
                'question' => 'Critical reminders through voice-overs',
                'impact_group_size' => 10,
                'occurrence_frequency' => 10,
                'experience_impact' => 10,
                'business_impact' => 10,
                'financial_feasibility' => 10,
                'technical_feasibility' => 10,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'survey_id' => 1,
                'question' => 'AI driven eCommerce for employees',
                'impact_group_size' => 10,
                'occurrence_frequency' => 10,
                'experience_impact' => 10,
                'business_impact' => 10,
                'financial_feasibility' => 10,
                'technical_feasibility' => 10,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'survey_id' => 1,
                'question' => 'Online support groups to share best practices & learning',
                'impact_group_size' => 10,
                'occurrence_frequency' => 10,
                'experience_impact' => 10,
                'business_impact' => 10,
                'financial_feasibility' => 10,
                'technical_feasibility' => 10,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'survey_id' => 1,
                'question' => 'Office should be converted to communal facilities',
                'impact_group_size' => 10,
                'occurrence_frequency' => 10,
                'experience_impact' => 10,
                'business_impact' => 10,
                'financial_feasibility' => 10,
                'technical_feasibility' => 10,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'survey_id' => 1,
                'question' => 'Eliminating hiring bias with AI',
                'impact_group_size' => 10,
                'occurrence_frequency' => 10,
                'experience_impact' => 10,
                'business_impact' => 10,
                'financial_feasibility' => 10,
                'technical_feasibility' => 10,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'survey_id' => 1,
                'question' => 'Wearable tech to monitor Workplace health',
                'impact_group_size' => 10,
                'occurrence_frequency' => 10,
                'experience_impact' => 10,
                'business_impact' => 10,
                'financial_feasibility' => 10,
                'technical_feasibility' => 10,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'survey_id' => 1,
                'question' => 'AI-based analytics tools to monitor meetings and emails overload',
                'impact_group_size' => 10,
                'occurrence_frequency' => 10,
                'experience_impact' => 10,
                'business_impact' => 10,
                'financial_feasibility' => 10,
                'technical_feasibility' => 10,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'survey_id' => 1,
                'question' => 'Putting more focus on cognitive diversity in a Team',
                'impact_group_size' => 10,
                'occurrence_frequency' => 10,
                'experience_impact' => 10,
                'business_impact' => 10,
                'financial_feasibility' => 10,
                'technical_feasibility' => 10,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'survey_id' => 1,
                'question' => 'AI based job suggestion pop-up',
                'impact_group_size' => 10,
                'occurrence_frequency' => 10,
                'experience_impact' => 10,
                'business_impact' => 10,
                'financial_feasibility' => 10,
                'technical_feasibility' => 10,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'survey_id' => 1,
                'question' => 'An internal online platform where employees can invest their skills',
                'impact_group_size' => 10,
                'occurrence_frequency' => 10,
                'experience_impact' => 10,
                'business_impact' => 10,
                'financial_feasibility' => 10,
                'technical_feasibility' => 10,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'survey_id' => 1,
                'question' => 'Git hub like software development platform',
                'impact_group_size' => 10,
                'occurrence_frequency' => 10,
                'experience_impact' => 10,
                'business_impact' => 10,
                'financial_feasibility' => 10,
                'technical_feasibility' => 10,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'survey_id' => 1,
                'question' => 'Build AI chatbot',
                'impact_group_size' => 10,
                'occurrence_frequency' => 10,
                'experience_impact' => 10,
                'business_impact' => 10,
                'financial_feasibility' => 10,
                'technical_feasibility' => 10,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'survey_id' => 1,
                'question' => 'Gamification of KPIs',
                'impact_group_size' => 10,
                'occurrence_frequency' => 10,
                'experience_impact' => 10,
                'business_impact' => 10,
                'financial_feasibility' => 10,
                'technical_feasibility' => 10,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'survey_id' => 1,
                'question' => 'Holographic meeting room',
                'impact_group_size' => 10,
                'occurrence_frequency' => 10,
                'experience_impact' => 10,
                'business_impact' => 10,
                'financial_feasibility' => 10,
                'technical_feasibility' => 10,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'survey_id' => 1,
                'question' => 'Smart integration of Collaboration, meassaging, ideation & learning tools',
                'impact_group_size' => 10,
                'occurrence_frequency' => 10,
                'experience_impact' => 10,
                'business_impact' => 10,
                'financial_feasibility' => 10,
                'technical_feasibility' => 10,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'survey_id' => 1,
                'question' => 'Online tests and assessments',
                'impact_group_size' => 10,
                'occurrence_frequency' => 10,
                'experience_impact' => 10,
                'business_impact' => 10,
                'financial_feasibility' => 10,
                'technical_feasibility' => 10,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'survey_id' => 1,
                'question' => 'Pulse survey tools',
                'impact_group_size' => 10,
                'occurrence_frequency' => 10,
                'experience_impact' => 10,
                'business_impact' => 10,
                'financial_feasibility' => 10,
                'technical_feasibility' => 10,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'survey_id' => 1,
                'question' => 'Online gaming',
                'impact_group_size' => 10,
                'occurrence_frequency' => 10,
                'experience_impact' => 10,
                'business_impact' => 10,
                'financial_feasibility' => 10,
                'technical_feasibility' => 10,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'survey_id' => 1,
                'question' => 'Modern ideation platforms',
                'impact_group_size' => 10,
                'occurrence_frequency' => 10,
                'experience_impact' => 10,
                'business_impact' => 10,
                'financial_feasibility' => 10,
                'technical_feasibility' => 10,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'survey_id' => 1,
                'question' => 'having fluid teams and workers with broad skill sets',
                'impact_group_size' => 10,
                'occurrence_frequency' => 10,
                'experience_impact' => 10,
                'business_impact' => 10,
                'financial_feasibility' => 10,
                'technical_feasibility' => 10,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'survey_id' => 1,
                'question' => 'Gamification For Goal Tracking',
                'impact_group_size' => 10,
                'occurrence_frequency' => 10,
                'experience_impact' => 10,
                'business_impact' => 10,
                'financial_feasibility' => 10,
                'technical_feasibility' => 10,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'survey_id' => 1,
                'question' => 'Real time feedback and performance management tools',
                'impact_group_size' => 10,
                'occurrence_frequency' => 10,
                'experience_impact' => 10,
                'business_impact' => 10,
                'financial_feasibility' => 10,
                'technical_feasibility' => 10,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'survey_id' => 1,
                'question' => 'Permenantly flexible future',
                'impact_group_size' => 10,
                'occurrence_frequency' => 10,
                'experience_impact' => 10,
                'business_impact' => 10,
                'financial_feasibility' => 10,
                'technical_feasibility' => 10,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'survey_id' => 1,
                'question' => 'Full Digitalization B2B sales',
                'impact_group_size' => 10,
                'occurrence_frequency' => 10,
                'experience_impact' => 10,
                'business_impact' => 10,
                'financial_feasibility' => 10,
                'technical_feasibility' => 10,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ]
        ];

        $questionsTable = $this->table('questions');
        $questionsTable->insert($questions)
            ->save();
    }
}
