<?php


use Phinx\Seed\AbstractSeed;

class QuestionsSeeder extends AbstractSeed
{
    /**
     * Run Method.
     *
     * Write your database seeder using this method.
     *
     * More information on writing seeders is available here:
     * http://docs.phinx.org/en/latest/seeding.html
     */
    public function run()
    {
        $questions = [
            [
                'survey_id' => 1,
                'question' => 'Office entry without ID card (Retina scan or proximity sensor etc.)',
                'impact_group_size' => 10,
                'occurrence_frequency' => 10,
                'experience_impact' => 10,
                'business_impact' => 10,
                'financial_feasibility' => 10,
                'technical_feasibility' => 10,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'survey_id' => 1,
                'question' => 'Virtual personal assistant for every employee',
                'impact_group_size' => 10,
                'occurrence_frequency' => 10,
                'experience_impact' => 10,
                'business_impact' => 10,
                'financial_feasibility' => 10,
                'technical_feasibility' => 10,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'survey_id' => 1,
                'question' => 'Create meeting minutes on voice command, send to intended recipients and make archives for quick reference',
                'impact_group_size' => 10,
                'occurrence_frequency' => 10,
                'experience_impact' => 10,
                'business_impact' => 10,
                'financial_feasibility' => 10,
                'technical_feasibility' => 10,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'survey_id' => 1,
                'question' => 'Online employee community for different references & recommendations',
                'impact_group_size' => 10,
                'occurrence_frequency' => 10,
                'experience_impact' => 10,
                'business_impact' => 10,
                'financial_feasibility' => 10,
                'technical_feasibility' => 10,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'survey_id' => 1,
                'question' => 'Contextual/personalized rewards for employees using analytics',
                'impact_group_size' => 10,
                'occurrence_frequency' => 10,
                'experience_impact' => 10,
                'business_impact' => 10,
                'financial_feasibility' => 10,
                'technical_feasibility' => 10,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'survey_id' => 1,
                'question' => 'AI-powered talent tool to predict future talent demands, search talent and eliminate hiring bias',
                'impact_group_size' => 10,
                'occurrence_frequency' => 10,
                'experience_impact' => 10,
                'business_impact' => 10,
                'financial_feasibility' => 10,
                'technical_feasibility' => 10,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'survey_id' => 1,
                'question' => 'Wearable tech to monitor Workplace wellbeing and keep social distancing',
                'impact_group_size' => 10,
                'occurrence_frequency' => 10,
                'experience_impact' => 10,
                'business_impact' => 10,
                'financial_feasibility' => 10,
                'technical_feasibility' => 10,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'survey_id' => 1,
                'question' => 'Build AI chatbot which will answer all types of employee queries',
                'impact_group_size' => 10,
                'occurrence_frequency' => 10,
                'experience_impact' => 10,
                'business_impact' => 10,
                'financial_feasibility' => 10,
                'technical_feasibility' => 10,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'survey_id' => 1,
                'question' => 'Gamification of KPIs & goal tracking',
                'impact_group_size' => 10,
                'occurrence_frequency' => 10,
                'experience_impact' => 10,
                'business_impact' => 10,
                'financial_feasibility' => 10,
                'technical_feasibility' => 10,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'survey_id' => 1,
                'question' => 'Modern ideation platforms to promote innovation',
                'impact_group_size' => 10,
                'occurrence_frequency' => 10,
                'experience_impact' => 10,
                'business_impact' => 10,
                'financial_feasibility' => 10,
                'technical_feasibility' => 10,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'survey_id' => 1,
                'question' => 'Employee data warehouse to take informed decisions about our people by using real time data and analytics',
                'impact_group_size' => 10,
                'occurrence_frequency' => 10,
                'experience_impact' => 10,
                'business_impact' => 10,
                'financial_feasibility' => 10,
                'technical_feasibility' => 10,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'survey_id' => 1,
                'question' => 'Interpreting employee emotions during virtual collaboration via a webcam',
                'impact_group_size' => 10,
                'occurrence_frequency' => 10,
                'experience_impact' => 10,
                'business_impact' => 10,
                'financial_feasibility' => 10,
                'technical_feasibility' => 10,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'survey_id' => 1,
                'question' => 'Augmented and Virtual reality (AR/VR) to turn any space into employee\'s own customizable workspace and gives him/her an immersive learning experience',
                'impact_group_size' => 10,
                'occurrence_frequency' => 10,
                'experience_impact' => 10,
                'business_impact' => 10,
                'financial_feasibility' => 10,
                'technical_feasibility' => 10,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'survey_id' => 1,
                'question' => 'AI-led video analysis to identify work style, collaboration potential, and general cognitive ability of an applicant during pre-hire assessments',
                'impact_group_size' => 10,
                'occurrence_frequency' => 10,
                'experience_impact' => 10,
                'business_impact' => 10,
                'financial_feasibility' => 10,
                'technical_feasibility' => 10,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'survey_id' => 1,
                'question' => 'Instead of one-time annual surveys, allow for frequent two-way conversations and real-time feedback between employee & machine (AI) to measure employee engagement.',
                'impact_group_size' => 10,
                'occurrence_frequency' => 10,
                'experience_impact' => 10,
                'business_impact' => 10,
                'financial_feasibility' => 10,
                'technical_feasibility' => 10,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'survey_id' => 1,
                'question' => 'A central go-to location for all employee information, resources and communication which is intuitive and easy to search',
                'impact_group_size' => 10,
                'occurrence_frequency' => 10,
                'experience_impact' => 10,
                'business_impact' => 10,
                'financial_feasibility' => 10,
                'technical_feasibility' => 10,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'survey_id' => 1,
                'question' => 'Get AI assisted research (internal/external) insights and automated document review and analysis',
                'impact_group_size' => 10,
                'occurrence_frequency' => 10,
                'experience_impact' => 10,
                'business_impact' => 10,
                'financial_feasibility' => 10,
                'technical_feasibility' => 10,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'survey_id' => 1,
                'question' => 'Allow crowdsourcing to obtain needed services, ideas, or content by soliciting contributions from a large group of people, especially from the online community rather than from traditional employees',
                'impact_group_size' => 10,
                'occurrence_frequency' => 10,
                'experience_impact' => 10,
                'business_impact' => 10,
                'financial_feasibility' => 10,
                'technical_feasibility' => 10,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'survey_id' => 1,
                'question' => 'Use sensors, AI software, and data analytics to track employees’ interactions to better understand the relationship between team-building and productivity',
                'impact_group_size' => 10,
                'occurrence_frequency' => 10,
                'experience_impact' => 10,
                'business_impact' => 10,
                'financial_feasibility' => 10,
                'technical_feasibility' => 10,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'survey_id' => 1,
                'question' => 'Connect the community of healthcare between employees, physicians and care teams with a cloud-based Virtual Care Management solution',
                'impact_group_size' => 10,
                'occurrence_frequency' => 10,
                'experience_impact' => 10,
                'business_impact' => 10,
                'financial_feasibility' => 10,
                'technical_feasibility' => 10,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'survey_id' => 1,
                'question' => 'Using video analytics software for CCTV and thermal cameras to determine whether social distancing is being maintained and monitor employee body temperature in real time, etc.',
                'impact_group_size' => 10,
                'occurrence_frequency' => 10,
                'experience_impact' => 10,
                'business_impact' => 10,
                'financial_feasibility' => 10,
                'technical_feasibility' => 10,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'survey_id' => 1,
                'question' => 'Using the lift by calling ahead and indicate the floor employee wants to go to using smartphone app.',
                'impact_group_size' => 10,
                'occurrence_frequency' => 10,
                'experience_impact' => 10,
                'business_impact' => 10,
                'financial_feasibility' => 10,
                'technical_feasibility' => 10,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'survey_id' => 1,
                'question' => 'Arrange multiplayer online role-playing games to build engagement as well as promoting ideal workplace behavior simulations',
                'impact_group_size' => 10,
                'occurrence_frequency' => 10,
                'experience_impact' => 10,
                'business_impact' => 10,
                'financial_feasibility' => 10,
                'technical_feasibility' => 10,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'survey_id' => 1,
                'question' => 'Virtual Room Collaboration Platform where team members can use holography, use whiteboard with editing tools, virtual brainstorming etc. in one convenient online location',
                'impact_group_size' => 10,
                'occurrence_frequency' => 10,
                'experience_impact' => 10,
                'business_impact' => 10,
                'financial_feasibility' => 10,
                'technical_feasibility' => 10,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'survey_id' => 1,
                'question' => 'Use sensor technology in Elevator buttons, washroom etc. to help curb the spread of bacteria and to reduce the need for employees to touch surfaces',
                'impact_group_size' => 10,
                'occurrence_frequency' => 10,
                'experience_impact' => 10,
                'business_impact' => 10,
                'financial_feasibility' => 10,
                'technical_feasibility' => 10,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'survey_id' => 1,
                'question' => 'Real time recognition and performance feedback via digital and automated technology',
                'impact_group_size' => 10,
                'occurrence_frequency' => 10,
                'experience_impact' => 10,
                'business_impact' => 10,
                'financial_feasibility' => 10,
                'technical_feasibility' => 10,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ]
        ];

        $questionsTable = $this->table('questions');
        $questionsTable->insert($questions)
            ->save();
    }
}
