<?php

namespace App\Controller;

use Slim\Http\Request;
use Slim\Http\Response;

/**
 * Class ProductsController
 *
 * @package App\Controller
 */
class ProductsController extends AppController
{
    /**
     * @throws \Interop\Container\Exception\ContainerException
     */
    public function beforeRender()
    {
        parent::beforeRender(); // TODO: Change the autogenerated stub
    }

    /**
     * @param Request  $request
     * @param Response $response
     * @param $args
     * @return \Psr\Http\Message\ResponseInterface
     * @throws \Interop\Container\Exception\ContainerException
     */
    public function products(Request $request, Response $response, $args)
    {
        $products = $this->loadModel()->getProductModel()->searchProducts($request->getQueryParams());
        $data = [
            'products' => $products,
        ];
        return $this->getView()->render($response, 'products/products.twig', $data);
    }

    /**
     * @param Request  $request
     * @param Response $response
     * @param $args
     * @return \Psr\Http\Message\ResponseInterface
     * @throws \Interop\Container\Exception\ContainerException
     */
    public function productDetails(Request $request, Response $response, $args)
    {
        $productSlug = $request->getAttribute('slug');
        $productUuid = $this->loadModel()->getProductModel()->getProductUuidBySlug($productSlug);
        $product = $this->loadModel()->getProductModel()->getProduct($productUuid);
        $data = [
            'product' => $product,
            'url' => $request->getUri()->getBaseUrl() . $request->getUri()->getPath()
        ];
        return $this->getView()->render($response, 'products/product-details.twig', $data);
    }
}