<?php

namespace App\Controller;

use App\helpers\Utility;
use Slim\Http\Request;
use Slim\Http\Response;

/**
 * Class SurveyController
 *
 * @package App\Controller
 */
class SurveyController extends AppController
{
    /**
     * @throws \Interop\Container\Exception\ContainerException
     */
    public function beforeRender()
    {
        parent::beforeRender(); // TODO: Change the autogenerated stub
    }

    /**
     * @param Request  $request
     * @param Response $response
     * @param $args
     * @return \Psr\Http\Message\ResponseInterface
     */
    public function start(Request $request, Response $response, $args)
    {
        $questions = $this->loadModel()->getQuestionsModel()->getAllQuestions();
        $data = [
            'questions' => $questions,
        ];
        return $this->getView()->render($response, 'survey/start.twig', $data);
    }

    /**
     * @param Request  $request
     * @param Response $response
     * @param $args
     * @return \Psr\Http\Message\ResponseInterface
     */
    public function collect(Request $request, Response $response, $args)
    {
        $data = $request->getParsedBody();
        var_dump($data);
        die();
    }
}
